"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Activity, CircleAlert, CircleStop, Edit3, Mail, Play, Plus, Radar, RefreshCw, RotateCw, Save, X } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:8000";
type Rule={id:string;product:string;extra_conditions:string|null;budget:string|null;exclude_keywords:string[];interval_minutes:number;is_enabled:boolean;next_run_at:string|null;emails:string[];parsed_requirement:{conditions?:string[]}|null};
type Task={id:string;status:string;stage:string;scraped_count:number;candidate_count:number;sent_count:number;error_message:string|null;started_at:string|null};
type Log={id:string;price:number;email:string;created_at:string};
type Draft={product:string;extra_conditions:string;budget:string;exclude_keywords:string;emails:string;interval_minutes:number;enabled:boolean};
const empty:Draft={product:"",extra_conditions:"",budget:"",exclude_keywords:"",emails:"",interval_minutes:15,enabled:true};
const stages:Record<string,string>={pending:"等待中",parsing:"解析条件",scraping:"检索商品",filtering:"规则筛选",ranking:"比较候选",sending:"发送邮件",done:"已完成",failed:"失败",stopped:"已停止"};
const parts=(s:string)=>s.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);
// 后端以 MySQL DATETIME 保存北京时间；无偏移字符串须显式按 +08:00 解释。
const date=(s:string|null)=>s?new Intl.DateTimeFormat("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Shanghai"}).format(new Date(/[zZ]$|[+-]\d\d:\d\d$/.test(s)?s:`${s}+08:00`)):"等待调度器计算";
async function call<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(`${API}${path}`,{...init,headers:{"Content-Type":"application/json",...init?.headers}});if(!r.ok){const b=await r.json().catch(()=>null);throw Error(b?.detail??`请求失败 (${r.status})`)}return r.json()}

export default function Home(){
 const [rules,setRules]=useState<Rule[]>([]),[picked,setPicked]=useState<string|null>(null),[tasks,setTasks]=useState<Task[]>([]),[logs,setLogs]=useState<Log[]>([]),[draft,setDraft]=useState<Draft>(empty),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[online,setOnline]=useState(false),[failure,setFailure]=useState<Task|null>(null);
 const current=rules.find(x=>x.id===picked)??null;
 const load=useCallback(async()=>{try{const items=await call<Rule[]>("/api/rules");setRules(items);setPicked(old=>items.some(x=>x.id===old)?old:items[0]?.id??null);setOnline(true)}catch(e){setOnline(false);setNotice(e instanceof Error?e.message:"无法连接后端")}},[]);
 const loadDetails=useCallback(async(id:string)=>{try{const [a,b]=await Promise.all([call<Task[]>(`/api/rules/${id}/tasks`),call<Log[]>(`/api/rules/${id}/history`)]);setTasks(a);setLogs(b)}catch(e){setNotice(e instanceof Error?e.message:"读取记录失败")}},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(picked)void loadDetails(picked)},[picked,loadDetails]);useEffect(()=>{const id=setInterval(()=>{void load();if(picked)void loadDetails(picked)},10000);return()=>clearInterval(id)},[load,loadDetails,picked]);
 const change=(key:keyof Draft,value:string|number|boolean)=>setDraft(v=>({...v,[key]:value}));
 async function save(e:FormEvent){e.preventDefault();const emails=parts(draft.emails);if(!draft.product.trim()||!emails.length){setNotice("请填写商品名称和至少一个收件邮箱");return}setBusy("save");try{const payload={product:draft.product.trim(),extra_conditions:draft.extra_conditions||null,budget:draft.budget||null,exclude_keywords:parts(draft.exclude_keywords),emails,interval_minutes:Number(draft.interval_minutes),enabled:draft.enabled};const rule=await call<Rule>(editing?`/api/rules/${editing}`:"/api/rules",{method:editing?"PUT":"POST",body:JSON.stringify(payload)});await load();setPicked(rule.id);setDraft(empty);setEditing(null);setNotice("规则已保存")}catch(err){setNotice(err instanceof Error?err.message:"保存失败")}finally{setBusy("")}}
 async function action(rule:Rule,kind:"run"|"start"|"stop"){setBusy(kind+rule.id);try{await call(kind==="run"?`/api/rules/${rule.id}/run`:`/api/rules/${rule.id}/${kind}`,{method:"POST"});await load();await loadDetails(rule.id);setNotice(kind==="run"?"任务已开始":kind==="start"?"监控已启用":"监控已停止")}catch(err){setNotice(err instanceof Error?err.message:"操作失败")}finally{setBusy("")}}
 function edit(r:Rule){setEditing(r.id);setDraft({product:r.product,extra_conditions:r.extra_conditions??"",budget:r.budget??"",exclude_keywords:r.exclude_keywords.join("，"),emails:r.emails.join("，"),interval_minutes:r.interval_minutes,enabled:r.is_enabled});window.scrollTo({top:0,behavior:"smooth"})}
 return <main className="shell"><aside className="rail"><div className="brand"><i><Radar size={18}/></i>闲鱼雷达</div><nav><span className="nav active"><Activity size={16}/>监控规则</span><span className="nav"><Mail size={16}/>推送记录</span></nav><p>本机运行<br/>采集、筛选与邮件推送</p></aside><section className="work"><header><div><h1>商品监控工作台</h1><p>设置一次，系统会持续检索闲鱼列表并发送新商品。</p></div><span className={`online ${online?"":"off"}`}>{online?"后端已连接":"后端未连接"}</span></header>
 <section className="stats"><div><small>启用中的规则</small><b>{rules.filter(x=>x.is_enabled).length}</b><em>共 {rules.length} 条规则</em></div><div><small>当前规则推送</small><b>{logs.length}</b><em>已发送商品数量</em></div><div><small>最近任务推送</small><b>{tasks[0]?.sent_count??"—"}</b><em>最新一次执行结果</em></div></section>
 <section className="composer"><div className="section-title">{editing?"编辑监控规则":"新建监控规则"}{editing&&<button className="text" type="button" onClick={()=>{setEditing(null);setDraft(empty)}}>取消编辑</button>}</div><form onSubmit={save}><label className="product">想找什么商品<input value={draft.product} onChange={e=>change("product",e.target.value)} placeholder="例如：MacBook M1 Pro"/></label><label>预算范围<input value={draft.budget} onChange={e=>change("budget",e.target.value)} placeholder="6000-8000（可空）"/></label><label>收件邮箱<input value={draft.emails} onChange={e=>change("emails",e.target.value)} placeholder="多个邮箱用逗号分隔"/></label><label className="wide">补充条件<textarea value={draft.extra_conditions} onChange={e=>change("extra_conditions",e.target.value)} placeholder="例如：16寸 32G+512G，成色好，无拆修"/></label><label>排除词<textarea value={draft.exclude_keywords} onChange={e=>change("exclude_keywords",e.target.value)} placeholder="维修机，企业管理机"/></label><label>执行频率<select value={draft.interval_minutes} onChange={e=>change("interval_minutes",Number(e.target.value))}>{[10,15,20,30].map(x=><option key={x}>{x}</option>)}</select></label><div className="form-end"><label className="toggle"><input type="checkbox" checked={draft.enabled} onChange={e=>change("enabled",e.target.checked)}/><span/>创建后自动启用</label><button className="primary" disabled={busy==="save"}>{editing?<Save size={15}/>:<Plus size={15}/>}{editing?"保存规则":"创建规则"}</button></div></form></section>
 <div className="list-head"><div><h2>监控规则</h2><p>后台会按 10–30 分钟随机间隔执行，页面时间均为北京时间。</p></div><button className="text" onClick={()=>void load()}><RefreshCw size={14}/>刷新</button></div><section className="rules">{rules.length===0?<div className="empty">还没有规则。填写上方表单后即可开始监控。</div>:rules.map(r=><article className={picked===r.id?"rule chosen":"rule"} key={r.id}><div className="name"><span className={r.is_enabled?"tag on":"tag"}>{r.is_enabled?"监控中":"已停止"}</span><button onClick={()=>setPicked(r.id)}>{r.product}</button><small>{r.extra_conditions||"未设置额外条件"}{r.budget?` · ¥${r.budget}`:" · 价格优先"}</small></div><div><strong>{r.emails.join("、")}</strong><small>每 {r.interval_minutes} 分钟检查</small></div><div><strong>{r.is_enabled?"下次执行":"监控已暂停"}</strong><small>{r.is_enabled?date(r.next_run_at):"启用后开始排程"}</small></div><div className="actions"><button title="编辑规则" onClick={()=>edit(r)}><Edit3 size={16}/></button><button title="立即执行" disabled={busy===`run${r.id}`} onClick={()=>void action(r,"run")}><Play size={16}/></button><button title={r.is_enabled?"停止监控":"启用监控"} className={r.is_enabled?"danger":""} onClick={()=>void action(r,r.is_enabled?"stop":"start")}>{r.is_enabled?<CircleStop size={16}/>:<RotateCw size={16}/>}</button></div></article>)}</section>
 {current&&<section className="records"><div><div className="section-title">{current.product} 的运行记录</div><table><thead><tr><th>开始时间</th><th>状态</th><th>阶段</th><th>采集 / 候选 / 推送</th><th>原因</th></tr></thead><tbody>{tasks.length?tasks.slice(0,8).map(t=><tr key={t.id}><td>{date(t.started_at)}</td><td className={t.status}>{t.status==="success"?"成功":t.status==="failed"?"失败":"执行中"}</td><td>{stages[t.stage]??t.stage}</td><td>{t.scraped_count} / {t.candidate_count} / {t.sent_count}</td><td>{t.status==="failed"?<button className="failure-button" onClick={()=>setFailure(t)}><CircleAlert size={14}/>查看原因</button>:"—"}</td></tr>):<tr><td colSpan={5}>等待首次执行</td></tr>}</tbody></table></div><aside><div className="section-title">需求解析</div><p className="hint">用于比较商品的条件</p><div className="chips">{current.parsed_requirement?.conditions?.map(x=><span key={x}>{x}</span>)??<span>将在第一次任务后生成</span>}</div><div className="section-title">已发送商品</div>{logs.length?logs.slice(0,5).map(x=><p className="mail" key={x.id}>¥{x.price}<span>{x.email}</span><small>{date(x.created_at)}</small></p>):<p className="empty">尚未发送商品</p>}</aside></section>}{failure&&<div className="dialog-backdrop" role="presentation" onMouseDown={()=>setFailure(null)}><section className="failure-dialog" role="dialog" aria-modal="true" aria-labelledby="failure-title" onMouseDown={e=>e.stopPropagation()}><div className="dialog-head"><div><span className="failure-icon"><CircleAlert size={17}/></span><h2 id="failure-title">任务失败原因</h2></div><button className="dialog-close" title="关闭" aria-label="关闭" onClick={()=>setFailure(null)}><X size={18}/></button></div><p className="dialog-time">开始时间：{date(failure.started_at)}（北京时间）</p><pre>{failure.error_message||"该任务未记录具体失败原因。"}</pre></section></div>}{notice&&<div className="toast">{notice}</div>}</section></main>
}
